import React from 'react';
import { Lightbulb, AlertTriangle, Shield, Users, Key, Terminal, CreditCard } from 'lucide-react';

const InsightsPanel = ({ insights = [] }) => {
  const getInsightIcon = (text) => {
    const lowerText = text.toLowerCase();
    if (lowerText.includes('password') || lowerText.includes('credential')) {
      return <Key className="w-4 h-4 text-red-500" />;
    }
    if (lowerText.includes('api key') || lowerText.includes('token')) {
      return <Key className="w-4 h-4 text-orange-500" />;
    }
    if (lowerText.includes('email') || lowerText.includes('pii')) {
      return <Users className="w-4 h-4 text-blue-500" />;
    }
    if (lowerText.includes('credit card')) {
      return <CreditCard className="w-4 h-4 text-red-500" />;
    }
    if (lowerText.includes('stack trace') || lowerText.includes('exception')) {
      return <Terminal className="w-4 h-4 text-yellow-500" />;
    }
    if (lowerText.includes('critical') || lowerText.includes('high risk')) {
      return <AlertTriangle className="w-4 h-4 text-red-500" />;
    }
    return <Shield className="w-4 h-4 text-indigo-500" />;
  };

  if (insights.length === 0) {
    return (
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 p-8 text-center">
        <Lightbulb className="w-12 h-12 text-gray-300 dark:text-gray-600 mx-auto mb-4" />
        <p className="text-gray-500 dark:text-gray-400">No insights available</p>
      </div>
    );
  }

  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 overflow-hidden">
      <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white flex items-center gap-2">
          <Lightbulb className="w-5 h-5 text-yellow-500" />
          AI Security Insights
        </h3>
      </div>

      <div className="p-6 space-y-4">
        {insights.map((insight, index) => (
          <div 
            key={index}
            className="flex items-start gap-4 p-4 bg-gray-50 dark:bg-gray-700/50 rounded-lg border-l-4 border-indigo-500 hover:bg-gray-100 dark:hover:bg-gray-700/70 transition-colors"
          >
            <div className="flex-shrink-0 mt-0.5">
              {getInsightIcon(insight)}
            </div>
            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
              {insight}
            </p>
          </div>
        ))}
      </div>

      <div className="px-6 py-3 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-700/30">
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Generated by AI analysis
        </p>
      </div>
    </div>
  );
};

export default InsightsPanel;